#include "flag.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#ifdef PTHREAD
  #include <pthread.h>
#endif
#include "constant.h"
#include "lmd2.h"
#include "lmd7.h"
#include "lmd8.h"
#include "simulthread.h"
#include "debug.h"
#include "spawn.h"
#include "spawn_xtrn.h"
#include "table.h"
#include "karacell.h"
#include "lmd_xtrn.h"
#include "karacell.c"
